---
# Ansible task template for inclusion in dependent projects that need a new database owned by a new database user

- name: Create postgres user
  postgresql_user: name='{{ db_user }}' password='{{ db_pass }}'
  sudo_user: postgres

- name: Create postgres database
  postgresql_db: name='{{ db_name }}' owner='{{ db_user }}' encoding='UTF-8' template=template0 lc_ctype='en_US.UTF-8' lc_collate='en_US.UTF-8'
  sudo_user: postgres
