---
- name: Install nginx package
  apt: name=nginx

- name: Create nginx app folders
  file: path=/etc/nginx/{{ item }} state=directory 
  with_items:
   - apps-available
   - apps-enabled

- name: Create nginx multi-app site
  template: dest=/etc/nginx/sites-available/multi src=nginx_multi.conf
  notify: restart nginx

- stat: path=/etc/nginx/sites-enabled/multi
  register: multi_file
- name: Enable nginx multi-app site
  file: path=/etc/nginx/sites-enabled/multi state=link src=/etc/nginx/sites-available/multi
  notify: restart nginx
  when: multi_file.stat.exists == False

- name: Disable nginix default site
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify: restart nginx

- name: Install ssl certificate
  copy: src=site.crt dest=/etc/ssl/certs/site.crt owner=root group=root mode=0644
  when: nginx_use_https
  notify: restart nginx

- name: Install ssl certificate key
  copy: src=site.key dest=/etc/ssl/private/site.key owner=root group=www-data mode=0640
  when: nginx_use_https
  notify: restart nginx

- name: Create /var/www directory
  file: path=/var/www state=directory owner=root group=root

- name: Start nginx
  service: name=nginx state=started enabled=yes
