---
- name: Install nginx package
  apt: name=nginx update_cache=yes cache_valid_time=86400

- name: Install password dependencies
  apt: name={{ item }}
  with_items:
   - python-passlib
   - apache2-utils
  when: nginx_create_user_file

- name: Start nginx
  service: name=nginx state=started enabled=yes

- name: Create nginx app folders
  file: path=/etc/nginx/{{ item }} state=directory 
  with_items:
   - apps-available
   - apps-enabled

- name: Create nginx multi-app site
  template: dest=/etc/nginx/sites-available/multi src=nginx_multi.conf
  notify: restart nginx

- name: Enable nginx multi-app site
  file: path=/etc/nginx/sites-enabled/multi state=link src=/etc/nginx/sites-available/multi
  notify: restart nginx

- name: Disable nginix default site
  file: path=/etc/nginx/sites-available/default state=absent
  notify: restart nginx

- name: Install ssl certificate
  copy: src=site.crt dest=/etc/ssl/certs/site.crt owner=root group=root mode=0644
  when: nginx_use_https
  notify: restart nginx

- name: Install ssl certificate key
  copy: src=site.key dest=/etc/ssl/private/site.key owner=root group=www-data mode=0640
  when: nginx_use_https
  notify: restart nginx

- name: Create nginx user file
  htpasswd: path={{ nginx_user_file }} name={{ nginx_username }} password={{ nginx_password }} owner=root group=www-data mode=0640 crypt_scheme=des_crypt
  when: nginx_create_user_file
