---
- name: Install Postgres packages
  apt: name={{ item }}
  with_items:
    - postgresql
    - python-psycopg2

- name: Ensure that the postgres user can be impersonated without password
  lineinfile: "dest=/etc/sudoers line='%sudo ALL=(postgres) NOPASSWD: ALL' validate='visudo -cf %s'"
  when: ansible_os_family == "Debian"

- name: Start PostgreSQL
  service: name=postgresql state=started enabled=yes
